### ISSUE TITLE
Shops & Traders Admin Shops Red Box Error

### ISSUE THREAD

**Issue by andrewmezzo** [Chuckleberry-Finn/pz-shops#36]
When clicking trade on an admin shop, it is throwing this .lua error on our dedicated server: 

`function: resetActivity -- file: shop-window.lua line # 1724 | MOD: Shops and Traders
function: onClick -- file: shop-window.lua line # 1447 | MOD: Shops and Traders
function: onMouseUp -- file: ISButton.lua line # 56 | Vanilla
java.lang.RuntimeException: attempted index of non-table
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaUtil.luaAssert(KahluaUtil.java:70)
    at se.krka.kahlua.vm.KahluaThread.tableSet(KahluaThread.java:1726)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:594)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallBoolean(KahluaThread.java:1924)
    at se.krka.kahlua.integration.LuaCaller.protectedCallBoolean(LuaCaller.java:104)
    at zombie.ui.UIElement.onMouseUp(UIElement.java:1228)
    at zombie.ui.UIElement.onMouseUp(UIElement.java:1183)
    at zombie.ui.UIManager.update(UIManager.java:816)
    at zombie.GameWindow.logic(GameWindow.java:262)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by Chuckleberry-Finn** [comment]
I'm not able to replicate this issue, but I'll keep an eye out for it.
