### ISSUE TITLE
Newest update allows selling with categories but seems to have broken adding through "Type"

### ISSUE THREAD

**Issue by thicc-penguin** [Chuckleberry-Finn/pz-shops#38]
The newest update: 3 Dec @ 1:29am, has fixed the problem with Better Sorting. However it isn't allowing adding certain items through "Type" that were previously added to (admin) shops. Previously we were able to simply type in the item ID's, but that now spams errors when selecting "Type." 

The mod is still useable for regular players as they still drag and drop items from the inventory to the shop window. That also solves it for admins. 

I apologize for the inconvenience, but thank you so much for your hard work on this amazing mod!

I'm posting a snippet of what is repeatedly spammed when selecting "Type" to add something and typing in a few strings. (To be specific, using Brita's, Base.L96 would start the spamming errors.)

`LOG  : General     , 1701620595161> 9,842,880,293> -----------------------------------------
STACK TRACE
-----------------------------------------
Callframe at: gsub
function: sanitizeString -- file: shop-itemDictionary.lua line # 75 | MOD: Shops and Traders
function: findMatchesFromItemDictionary -- file: shop-itemDictionary.lua line # 88 | MOD: Shops and Traders
function: validateAddStockEntry -- file: shop-window.lua line # 1284 | MOD: Shops and Traders
function: render -- file: shop-window.lua line # 1419 | MOD: Shops and Traders

ERROR: General     , 1701620595187> 9,842,880,319> ExceptionLogger.logException> Exception thrown se.krka.kahlua.vm.KahluaException: invalid capture index at StringLib.addString line:1550.
ERROR: General     , 1701620595187> 9,842,880,319> DebugLogStream.printException> Stack trace:
se.krka.kahlua.vm.KahluaException: invalid capture index
	at se.krka.kahlua.stdlib.StringLib.addString(StringLib.java:1550)
	at se.krka.kahlua.stdlib.StringLib.addValue(StringLib.java:1510)
	at se.krka.kahlua.stdlib.StringLib.gsub(StringLib.java:1464)
	at se.krka.kahlua.stdlib.StringLib.call(StringLib.java:127)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
	at zombie.ui.UIElement.render(UIElement.java:1534)
	at zombie.ui.UIManager.render(UIManager.java:446)
	at zombie.gameStates.IngameState.renderFrameUI(IngameState.java:1183)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.gameStates.IngameState.renderframeui(IngameState.java:1172)
	at zombie.gameStates.IngameState.renderInternal(IngameState.java:1324)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.gameStates.IngameState.render(IngameState.java:1271)
	at zombie.gameStates.GameStateMachine.render(GameStateMachine.java:37)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.GameWindow.renderInternal(GameWindow.java:340)
	at zombie.GameWindow.frameStep(GameWindow.java:774)
	at zombie.GameWindow.run_ez(GameWindow.java:667)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by Chuckleberry-Finn** [comment]
Freshest update should fix this. Thank you.
